version: '3.9'

services:
  db:
    image: postgres:14.8
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: db
    container_name: db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d db -U user']
      interval: 3s
      timeout: 2s
      retries: 100
    networks:
      - default

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: webapp
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

volumes:
  db-data:

networks:
  default:
