version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: webapp
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
